import Head from 'next/head'
import Image from 'next/image'
import Card from '../component/banner/Card.js'
import Banner from '../component/banner/index.js'
import styles from '../styles/Home.module.css'
import coffeeStores from '../data/coffee-stores.json'
export async function getStaticProps(context) {
  return {
    props: {
      coffeeStoresData: coffeeStores
    }, // will be passed to the page component as props
  }
}

export default function Home(props) {
  const buttonHandler = () => {
    console.log('Hey Banner')
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        <meta name="description" content="Generated by Muneeb Nawaz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText='View stores nearby'
          buttonHandler={buttonHandler}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" alt='404' width={700} height={400} />
        </div>
        {props.coffeeStoresData.length > 0 &&
          <div>
            <h2 className={styles.heading2}>
              Toronto Stores
            </h2>
            <div className={styles.cardLayout}>
              {
                coffeeStores.map((data, index) => {
                  return (
                    <Card key={data.id}
                      title={data.name}
                      imageSrc={data.imgUrl}
                      href={`/coffee-store/${data.id}`}
                      className={styles.card} />
                  )
                })
              }
            </div>
            <div />
          </div>}
      </main>

    </div>
  )
}
